version: '3'

services:
  openvas:
    image: mikesplain/openvas
    ports:
      - "9443:443"
      - "9492:9392"
    volumes:
      - openvas-data:/var/lib/openvas/mgr

  metasploitable:
    image: tleemcjr/metasploitable2
    ports:
      - "2222:22"    # SSH
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "3306:3306"  # MySQL
      - "5900:5900"  # VNC
    command: /bin/bash -c "while true; do sleep 1000; done"

volumes:
  openvas-data:
